/* SCHEDULE.js */
(function (global) {
'use strict';
function toNum(v){if(v==null||v==='') return 0;const n=parseFloat(String(v).replace(/,/g,'').trim());return isNaN(n)?0:n;}
function parseDate(s){if(!s)return null;if(s instanceof Date)return isNaN(s.getTime())?null:s;const str=String(s).trim();let m=str.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);const d=new Date(str);return isNaN(d.getTime())?null:d;}
function fmtDate(d){if(!d)return '';const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const dd=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${dd}`;}
function processItemsTab(rows){return (rows||[]).map(r=>{const s=parseDate(r.startDate);const e=parseDate(r.endDate);const days=(s&&e)?Math.max(1,Math.round((e-s)/86400000)+1):0;return {item:(r.item||'').trim(),startDate:fmtDate(s),endDate:fmtDate(e),days};}).filter(r=>r.item).sort((a,b)=>(a.startDate||'').localeCompare(b.startDate||''));}
function processPlanTab(rows,opts){opts=opts||{};const cleaned=(rows||[]).map(r=>({date:parseDate(r.date),plannedValue:toNum(r.plannedValue||r.value)})).filter(r=>r.date).sort((a,b)=>a.date-b.date);const sum=cleaned.reduce((a,r)=>a+r.plannedValue,0);const total=toNum(opts.totalValue)>0?toNum(opts.totalValue):sum;let cumVal=0;let cumPct=0;return cleaned.map(r=>{cumVal+=r.plannedValue;const dailyPct=total>0?(r.plannedValue/total)*100:0;cumPct+=dailyPct;return {date:fmtDate(r.date),plannedValue:r.plannedValue,cumValue:+cumVal.toFixed(2),dailyPct:+dailyPct.toFixed(2),cumPct:+Math.min(cumPct,100).toFixed(2)};});}
function buildPlanFromItems(items){const merge={};(items||[]).forEach(it=>{const s=parseDate(it.startDate);const e=parseDate(it.endDate);const v=toNum(it.value);if(!s||!e||v<=0)return;const days=Math.max(1,Math.round((e-s)/86400000)+1);const per=v/days;for(let i=0;i<days;i++){const d=new Date(s.getFullYear(),s.getMonth(),s.getDate()+i);const k=fmtDate(d);merge[k]=(merge[k]||0)+per;}});return Object.keys(merge).sort().map(d=>({date:d,plannedValue:+merge[d].toFixed(2)}));}
global.Schedule={processItemsTab,processPlanTab,buildPlanFromItems};
})(window);